services:
  - type: web
    name: pvcclw
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 120 --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: pvcclw-db
          property: connectionString

databases:
  - name: pvcclw-db
    plan: free
    databaseName: pvc_db
    user: pvcuser
